id: PCD4F42C4
initial_creation_type: ocr
source_metadata:
  volumes:
    9787667604244bfdb89826768d2a6909:
      base_file: v116.txt
      image_group_id: I1PD95961
      title: བྱང་ཆུབ་འབྱུང་བའི་སྨོན་ལམ།
      total_pages: 1880
      volume_number: 116
