id: D6A6696A9
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-12-31T06:49:01+00:00'
last_modified: '2022-05-30T06:30:31.799814+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    d2b4:
      image_group_id: I1PD95961
      title: བྱང་ཆུབ་འབྱུང་བའི་སྨོན་ལམ།
      total_pages: 1880
      order: 116
      base_file: d2b4.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
